name: Pull Request builds

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: cd build/; mkdir ${{ github.head_ref	}}; mv * -t ${{ github.head_ref	}}
        shell: bash --noprofile --norc {0}
      - name: Deploy to PR build repo GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.PR_DEPLOY_SSH_KEY }}
          publish_dir: ./build
          publish_branch: master
          external_repository: thristhart/untitled-incremental-game-pr-builds
      - name: PR Comment	
        uses: github-actions-up-and-running/pr-comment@v1.0.0	
        with:	
          repo-token: ${{ secrets.GITHUB_TOKEN }}	
          message: View the latest successful build at https://thristhart.github.io/untitled-incremental-game-pr-builds/${{ github.head_ref	}}/
