name: Pull Request builds

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: echo "${{ secrets.PR_DEPLOY_SSH_KEY }}" > pr_deploy_ssh_key
        
      - name: git clone and deploy
        env:
          GIT_SSH_COMMAND: ssh -i pr_deploy_ssh_key
        run: |
          git clone git@github.com:Thristhart/untitled-incremental-game-pr-builds.git
          mv build/* untitled-incremental-game-pr-builds/${{ github.head_ref }}
          cd untitled-incremental-game-pr-builds
          git add ${{ github.head_ref }}
          git commit -m "deploy PR build for ${{ github.head_ref }}"
          git push
      - name: PR Comment	
        uses: github-actions-up-and-running/pr-comment@v1.0.0	
        with:	
          repo-token: ${{ secrets.GITHUB_TOKEN }}	
          message: View the latest successful build at https://thristhart.github.io/untitled-incremental-game-pr-builds/${{ github.head_ref	}}/
