name: Pull Request builds

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          # Artifact name
          name: ${{ github.head_ref	}}/${{ github.sha }}
          # Directory containing files to upload
          path: ./build
