name: Pull Request builds

on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: echo "${{ secrets.PR_DEPLOY_SSH_KEY }}" > pr_deploy_ssh_key
      - run: chmod 600 pr_deploy_ssh_key
        
      - name: git clone and deploy
        env:
          GIT_SSH_COMMAND: ssh -i pr_deploy_ssh_key -o "StrictHostKeyChecking=no"
        run: |
          git clone git@github.com:Thristhart/untitled-incremental-game-pr-builds.git
          rm -rf untitled-incremental-game-pr-builds/${{ github.head_ref }}
          mkdir -p untitled-incremental-game-pr-builds/${{ github.head_ref }}
          mv build/* untitled-incremental-game-pr-builds/${{ github.head_ref }}
          cd untitled-incremental-game-pr-builds
          git add ${{ github.head_ref }}
          git diff-index --quiet HEAD || (git commit -m "deploy PR build for ${{ github.head_ref }}" && git push)
  comment:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: View the latest successful build at https://thristhart.github.io/untitled-incremental-game-pr-builds/${{ github.head_ref	}}/
          check_for_duplicate_msg: true
